name: Bug
description: Report a validated bug -- NOT FOR SUPPORT REQUESTS
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        name

  - type: input
    id: system-details
    attributes:
      label: System details
      placeholder: e.g. AMD 9950X, NVIDIA 5090
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: What's wrong?
      description: Describe the issue, include steps to recreate it if possible
    validations:
      required: true
