name: Documentation
description: New pages or changes to existing
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
      name

  - type: textarea
    id: steps
    attributes:
      label: What correction or addition do we need?
      description: Please provide reference links and specifics of what should be updated
    validations:
      required: true
